package com.vjgarcia.currencyflags

object CurrencyFlags {

    val byISOCode: Map<String, Int> =
        mapOf(
            "AED" to R.drawable.aed,
            "ARS" to R.drawable.ars,
            "AUD" to R.drawable.aud,
            "BDT" to R.drawable.bdt,
            "BGN" to R.drawable.bgn,
            "BRL" to R.drawable.brl,
            "CAD" to R.drawable.cad,
            "CHF" to R.drawable.chf,
            "CLP" to R.drawable.clp,
            "CNY" to R.drawable.cny,
            "CRC" to R.drawable.crc,
            "CZK" to R.drawable.czk,
            "DKK" to R.drawable.dkk,
            "EGP" to R.drawable.egp,
            "EUR" to R.drawable.eur,
            "GBP" to R.drawable.gbp,
            "GEL" to R.drawable.gel,
            "GHS" to R.drawable.ghs,
            "HKD" to R.drawable.hkd,
            "HRK" to R.drawable.hrk,
            "HUF" to R.drawable.huf,
            "IDR" to R.drawable.idr,
            "ILS" to R.drawable.ils,
            "INR" to R.drawable.inr,
            "ISK" to R.drawable.isk,
            "JPY" to R.drawable.jpy,
            "KES" to R.drawable.kes,
            "KRW" to R.drawable.krw,
            "LKR" to R.drawable.lkr,
            "MAD" to R.drawable.mad,
            "MXN" to R.drawable.mxn,
            "MYR" to R.drawable.myr,
            "NGN" to R.drawable.ngn,
            "NOK" to R.drawable.nok,
            "NPR" to R.drawable.npr,
            "NZD" to R.drawable.nzd,
            "PEN" to R.drawable.pen,
            "PHP" to R.drawable.php,
            "PKR" to R.drawable.pkr,
            "PLN" to R.drawable.pln,
            "RON" to R.drawable.ron,
            "RUB" to R.drawable.rub,
            "SEK" to R.drawable.sek,
            "SGD" to R.drawable.sgd,
            "THB" to R.drawable.thb,
            "TRY" to R.drawable.try_,
            "TZS" to R.drawable.tzs,
            "UAH" to R.drawable.uah,
            "UGX" to R.drawable.ugx,
            "USD" to R.drawable.usd,
            "VND" to R.drawable.vnd,
            "XOF" to R.drawable.xof,
            "ZAR" to R.drawable.zar
        )
}